const SubscriptionActionTypes = {
  ADD_SUBSCRIPTION: 'ADD_SUBSCRIPTION',
  LOAD_SUBSCRIPTIONS: 'LOAD_SUBSCRIPTIONS',
  DELETE_SUBSCRIPTION: 'DELETE_SUBSCRIPTION',
  UPDATE_SUBSCRIPTION: 'UPDATE_SUBSCRIPTION'
};

export default SubscriptionActionTypes;
